version: "3"

services:
  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      lavalink:
        condition: service_started
      gateway:
        condition: service_started

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=riptide
      - POSTGRES_PASSWORD=riptide
      - POSTGRES_DATABASE=riptide
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riptide"]
      interval: 10s
      timeout: 5s
      retries: 5

  lavalink:
    build:
      context: .
      dockerfile: docker/lavalink/Dockerfile
    restart: unless-stopped

  gateway:
    build:
      dockerfile: docker/gateway/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    restart: unless-stopped
    ports:
      - "9999:9999"
      - "8086:8086"
    volumes:
      - "influxdb:/root/.influxdbv2"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 10s
      timeout: 5s

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      timeout: 5s

volumes:
  influxdb:
  grafana:
  prometheus:
