name: Publish Worker Docker Image
on:
  push:
    branches:
      - master
    paths:
      - "gateway/**"

jobs:
  push:
    name: Push Worker Docker Image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: diced/riptide/worker
          dockerfile: docker/gateway/Dockerfile
          tag_with_ref: true
