name: Publish Gateway Docker Image
on:
  push:
    branches:
      - master
    paths:
      - 'gateway/**'
      - ".github/workflows/push-gateway.yml"

jobs:
  push:
    name: Push Gateway Docker Image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: diced/riptide/gateway
          dockerfile: docker/gateway/Dockerfile
          tag_with_ref: true
